from langchain_core.tools import BaseTool, tool
from pydantic import BaseModel, Field

from openweatherclient import OpenWeatherClient
# from rag_main import rag_answer_generator  # Not currently used, but available if needed
from rag_pipelines import document_retrieval_pipeline

class GetWeatherInfoInput(BaseModel):
    city: str = Field(description="Location for which we need weather information.")

@tool("get_weather_info_by_location", args_schema=GetWeatherInfoInput)
def get_weather_info_by_location(city:str):
    """Get weather information for the given location(city)
    Args:
        Input:
        city: str - Location for which we need weather information.
        
        Output:
        response: dict - Weather info from Open weather client in JSON.
        
    """
    client = OpenWeatherClient()
    weather = client.get_weather_by_location(city=city)
    return weather

class RAGInput(BaseModel):
    query: str = Field(description="Query asked by the user.")
    
# @tool("get_answer_through_rag", args_schema=RAGInput)
# def get_answer_through_rag(query:str):
#     """Generate answer to the user query using RAG.
#     Args:
#         Input:
#         query: str - Query asked by the user.
        
#         Output:
#         response: dict - Answer Generated by rag.
    
#     """
#     resposne = rag_answer_generator(query)
#     return resposne

@tool("get_context_for_query", args_schema=RAGInput)
def get_context_for_query(query:str):
    """
    Get context through vector search(embeddings) for the user query,
    Args:
        Input: 
            query: str - Query asked by the user
        Output:
            context: str - Context extracted by vector search in vector DB
    """
    context, _, _ = document_retrieval_pipeline(query=query, top_k=3)
    return context


tools = [get_weather_info_by_location, get_context_for_query]

def format_tool_description(tools: list[BaseTool]) ->str:
    return "\n".join([f"- {tool.name}: {tool.description} \n Input arguments: {tool.args}" for tool in tools])

